### ISSUE TITLE
Não está definida uma licença

### ISSUE THREAD

**Issue by augusto-herrmann** [okfn-brasil/pedidosanonimos#16]
Este projeto pretende se tornar software livre? Em caso afirmativo, é necessário estabelecer uma licença, de preferência em um arquivo `LICENSE.txt` ou `LICENSE.md`, já que assim o Github já reconhece.

**Comment by vitorbaptista** [comment]
Obrigado pela lembrança, Augusto. Adicionei a licença MIT.
