### ISSUE TITLE
Erro na pagina.

### ISSUE THREAD

**Issue by gladson** [okfn-brasil/pedidosanonimos#18]
Por acaso ainda esta on o projeto, porque esta ativo o modo debug.

![image](https://user-images.githubusercontent.com/1013698/222317678-d39a7b57-d9d9-4f75-939b-78f5073b2c7f.png)
![image](https://user-images.githubusercontent.com/1013698/222318145-04c79569-bf01-4922-a8c1-b1e8ed15dedb.png)

**Comment by vitorbaptista** [comment]
Opa, obrigado @gladson. Desativei o modo debug.
