### ISSUE TITLE
Cadastro de órgão federal ou por região

### ISSUE THREAD

**Issue by ltartari** [okfn-brasil/pedidosanonimos#4]
Permitir cadastro de órgão federal ou de região específica.

Exemplos: Tribunal Superior Eleitoral (http://www.tse.jus.br/), Tribunal Regional Federal da 4ª Região (https://www.trf4.jus.br/trf4/).

**Comment by itepifanio** [comment]
Como seria esse fluxo? Cadastro simples por qualquer usuário, ou após submetido o orgão precisa ser aceito por alguém?

**Comment by ltartari** [comment]
Boa pergunta, @itepifanio 🤔

O fluxo pode permanecer igual ao que já existe implementado para criação de órgão… vejo que isso seria apenas uma nova opção para selecionar órgão federal ou região (não atrelado a nenhuma UF específica).

Acredito que o sistema não faça moderação automática (certo, @vitorbaptista ?). Se houver moderação o ideal seria isso ocorrer após a criação do órgão/pedido (só pra evitar de travar uma pessoa que esteja adicionando um órgão para fazer um novo pedido).

Faz sentido?

**Comment by itepifanio** [comment]
Entendi sim, posso trabalhar nessa issue?

**Comment by vitorbaptista** [comment]
Putz! Desculpem pela demora.

Não há moderação automática.

Com relação a solução, imagino adicionar um campo "Esfera" (em inglês, "level") depois do campo nome, podendo ser:

* Municipal (em inglês, local)
* Estadual (em inglês, state)
* Federal (em inglês, federal)

Por padrão, no formulário está "Municipal".

Daí, com JS desabilitamos o Estado/Cidade, dependendo da esfera escolhida (desabilitar, não esconder). Caso seja Estadual, exige Estado, caso Municipal, exige Estado e Cidade, e caso Federal, nada.

Também é importante fazer uma migração dos dados atuais, pra popular a esfera do que a gente já tem. 

@itepifanio Você tá com tempo pra pegar essa issue? :)

**Comment by itepifanio** [comment]
Entendi, posso fazer no fim de semana (meu período acaba na quinta), tudo bem?

**Comment by vitorbaptista** [comment]
@itepifanio Maravilha! Se algo não tiver ficado claro, ou você tiver qualquer outra dúvida, só mandar uma mensagem.

**Comment by itepifanio** [comment]
@vitorbaptista a parte mais simples está pronta, só não entendi essa migração que você falou, seria verificar a esfera dos orgãos cadastrados anteriormente?

Outra coisa, o disabled ou readonly do materialize é bem discreto pro usuário, só evita dele clicar lá, mas visualmente não tem muitas alterações.

**Comment by itepifanio** [comment]
Entendi, do [jeito que fiz](https://github.com/okfn-brasil/pedidosanonimos/pull/7) adicionei um "default" no model, então o load_fixtures já fica com o valor padrão quando roda, caso as próximas sejam diferentes basta adicionar no json um ` 'level' : 'outro valor' ` que será preenchido outro valor.

(Daqui a pouco vejo o erro no pep8 do pull)
