### ISSUE TITLE
Ordenar alfabeticamente a lista de órgãos públicos

### ISSUE THREAD

**Issue by vitorbaptista** [okfn-brasil/pedidosanonimos#8]
Para facilitar a busca por órgãos públicos, a lista de órgãos em https://queremossaber.org.br/p/new/ e no Django Admin deve estar ordenada alfabeticamente.

**Comment by phsetti** [comment]
Hi @vitorbaptista I would like to help :)

**Comment by vitorbaptista** [comment]
@phsetti Thanks! Feel free to tackle this issue and send a pull request whenever you're ready or would like some feedback.

I think this issue will be solved on this file: https://github.com/okfn-brasil/pedidosanonimos/blob/cbe26571483b5cf0acd838785635d03b57a2c164/web/foi_requests/models.py#L63 (or maybe on the respective model's Form, I'm not sure)

**Comment by vitorbaptista** [comment]
Fixed. Thanks @phsetti :tada:
